FROM node:22.9.0-alpine3.20

LABEL org.opencontainers.image.description="Spock.js documentation site (VitePress, development)"

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm i --loglevel=error --ignore-scripts --no-fund

CMD [ "node", "--run", "dev" ]
